version: 2.1
orbs:
  cypress: cypress-io/cypress@1 
  heroku: circleci/heroku@0

workflows:
  test_then_build:
    jobs:
      - cypress/run:
          start: npm run serve 
          wait-on: 'http://localhost:8080'  
      - heroku/deploy-via-git:
        requires:
          - cypress/run
